// DoD #7: DESIGN_PROMPT.md (what Claude Design was told) must match the code that loads its files.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const L = require('../logic.js');

const root = path.join(__dirname, '..');
const prompt = fs.readFileSync(path.join(root, 'DESIGN_PROMPT.md'), 'utf8');
const section = (from, to) => prompt.slice(prompt.indexOf(from), prompt.indexOf(to));

test('the state table in DESIGN_PROMPT.md is exactly PET_STATES, in order', () => {
  const table = section('## 4. Deliverable 2', '**Motion principles**');
  const names = table.split('\n').filter((l) => /^\| `/.test(l)).map((l) => /^\| `([a-z]+)`/.exec(l)[1]);
  assert.deepEqual(names, L.PET_STATES);
});

test('the idle variants in DESIGN_PROMPT.md are exactly IDLE_VARIANTS', () => {
  const table = section('## 4. Deliverable 2', '**Motion principles**');
  const idleRow = table.split('\n').find((l) => /^\| `idle`/.test(l));
  const variants = [...idleRow.matchAll(/`([a-d])`/g)].map((m) => m[1]);
  assert.deepEqual(variants, L.IDLE_VARIANTS);
});

test('the pet.css section of the prompt names every state and every idle variant', () => {
  const css = section('2. **`pet.css`**', '3. **`ui.css`**');
  for (const s of L.PET_STATES) assert.ok(css.includes(s), 'state missing from the pet.css section: ' + s);
  for (const v of L.IDLE_VARIANTS) assert.ok(css.includes(`"${v}"`), 'idle variant missing: ' + v);
  assert.match(css, /prefers-reduced-motion/);
});

test('every ql-* class in the DOM contract exists in index.html or is generated by app.js', () => {
  const dom = section('3. **`ui.css`**', '4. **`icons.svg`**');
  const wanted = new Set(dom.match(/\bql-[a-z0-9_-]+/g));
  const code = fs.readFileSync(path.join(root, 'index.html'), 'utf8') + fs.readFileSync(path.join(root, 'app.js'), 'utf8');
  const missing = [...wanted].filter((c) => !code.includes(c));
  assert.deepEqual(missing, [], 'classes promised to Claude Design but absent from the code: ' + missing.join(', '));
});

test('the code uses no ql-* class the contract does not know (Claude Design would not style it)', () => {
  const dom = section('3. **`ui.css`**', '4. **`icons.svg`**');
  const known = new Set(dom.match(/\bql-[a-z0-9_-]+/g));
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
  // the prompt lists the card variants as a comment "--ask|--step|..." and the seg states as is-*; expand them
  const extra = new Set();
  const variants = /<!-- --(.+?) -->/.exec(dom);
  if (variants) variants[1].split('|').forEach((v) => extra.add('ql-card--' + v.replace(/^--/, '')));
  const used = new Set([...html.matchAll(/\bql-[a-z0-9_-]+/g)].map((m) => m[0]).concat([...app.matchAll(/'(ql-[a-z0-9_-]+)/g)].map((m) => m[1]), [...app.matchAll(/ql-card--\$\{/g)].map(() => 'ql-card--ask')));
  const unknown = [...used].filter((c) => !known.has(c) && !extra.has(c));
  assert.deepEqual(unknown, [], 'classes in the code but missing from the DESIGN_PROMPT contract: ' + unknown.join(', '));
});
