const { _electron } = require('playwright-core');
const fs = require('fs'), os = require('os'), path = require('path');
const Q = require('node:path').resolve(__dirname, '..').split(require('node:path').sep).join('/');
let pass = 0, fail = 0;
const ok = (c, m) => { c ? pass++ : fail++; console.log((c ? 'PASS ' : 'FAIL ') + m); };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const ud = fs.mkdtempSync(path.join(os.tmpdir(), 'ql-ud-'));
  const env = { ...process.env, QUESTLING_TEST: '1', QUESTLING_MOCK: '1', QUESTLING_LEDGER_PATH: path.join(ud, 'usage.jsonl') };
  delete env.ELECTRON_RUN_AS_NODE;
  const app = await _electron.launch({ executablePath: Q + '/node_modules/electron/dist/electron.exe', args: [Q, '--user-data-dir=' + ud], env });
  const page = await app.firstWindow();
  const errs = [];
  page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
  page.on('pageerror', (e) => errs.push(String(e)));
  await page.waitForSelector('#bar');
  await page.click('#toggle');
  await page.fill('#task-text', 'my water cycle essay');
  await page.click('#make-quests');
  await page.waitForSelector('.ql-quest');
  ok((await page.$$('.ql-quest')).length === 3, 'quests rendered (3, mock/fallback v2)');
  ok((await page.textContent('.ql-pill')).includes('5'), 'minutes pill shows first quest 5 min');
  ok((await page.$$('.ql-seg')).length === 4, 'progress: plan segment + 3 quests');
  await page.click('#start-btn');
  await page.waitForSelector('.ql-window');
  await page.click('.ql-window'); await page.click('#windows-start');
  await page.waitForSelector('#stuck-btn:not(.hidden)');
  if (await page.isVisible('.ql-card--starter')) await page.click('#card-quiet');
  ok(await page.getAttribute('main', 'data-pet-state') === 'working', 'session on -> pet working');
  await page.click('#stuck-btn');
  await page.waitForSelector('.ql-card--step:not(.hidden)');
  ok(/rough sentence/.test(await page.textContent('#card-body')), 'stuck -> step card with mock nextStep');
  ok(await page.getAttribute('main', 'data-pet-state') === 'helper', 'step card -> pet helper');
  await page.click('#card-quiet');
  await page.waitForSelector('.ql-card--step:not(.hidden)');
  ok(true, 'Another idea -> new step card');
  await page.click('#card-primary');
  ok(await page.isVisible('#card-count'), 'Start 2 min -> countdown shown');
  ok(/^\d:\d\d$/.test(await page.textContent('#card-count-text')), 'countdown text m:ss');
  await page.click('#card-x');
  await page.click('#done-btn');
  await page.waitForSelector('.ql-card--confirm:not(.hidden)');
  ok(await page.$$eval('.ql-quest input[type=checkbox]', (b) => b.every((x) => !x.checked)), 'done look proposes; nothing completed');
  await page.click('#card-quiet');
  ok(await page.$$eval('.ql-quest input[type=checkbox]', (b) => b.every((x) => !x.checked)), 'Not yet -> still nothing completed');
  await page.click('#done-btn');
  await page.waitForSelector('.ql-card--confirm:not(.hidden)');
  await page.click('#card-primary');
  ok(await page.$$eval('.ql-quest input[type=checkbox]', (b) => b[0].checked && !b[1].checked), 'Yes, done -> quest 1 done, 2 not');
  // window lost -> asleep + repick
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('signal', { ts: Date.now(), changed: false, fgHwnd: 0, onWork: false, windowAlive: false, windowVisible: false, idleSec: 0, locked: false }));
  const t0 = Date.now();
  await page.waitForFunction(() => document.querySelector('main').dataset.petState === 'asleep', null, { timeout: 5000 });
  ok(Date.now() - t0 < 5000, 'window lost -> asleep in <5 s');
  ok(await page.isVisible('#repick'), 'Pick window again visible');
  await page.click('#repick');
  ok(await page.isVisible('.ql-window'), 'repick opens the picker');
  await page.click('.ql-window'); await page.click('#windows-start');
  await page.waitForFunction(() => document.querySelector('main').dataset.petState === 'working');
  ok(true, 're-pick -> working again');
  // paused done-check still gives a template confirm card
  await page.click('#pause-btn');
  await page.click('#done-btn');
  await page.waitForSelector('.ql-card--confirm:not(.hidden)');
  ok(/can't tell/.test(await page.textContent('#card-body')), 'paused: done -> local template confirm (no frame, no model)');
  const dump = await page.evaluate(() => JSON.stringify(localStorage));
  ok(!/data:image|base64/.test(dump), 'localStorage has no data:image/base64');
  ok(errs.length === 0, 'no console/CSP errors ' + JSON.stringify(errs.slice(0, 3)));
  await app.close();
  console.log(`\n${pass} pass, ${fail} fail`);
  process.exit(fail ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
